-- Centrum authentication security suite:
-- - staff MFA enforcement at the RLS authorization boundary
-- - customer/subscriber linking requests with staff approval
-- - trusted-browser records for new-login alerts
-- - security notifications that cannot be disabled

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'profiles' and column_name = 'subscription_verified'
  ) then
    alter table public.profiles add column subscription_verified boolean not null default false;
    -- Existing accounts predate the linking workflow and must keep their current service access.
    update public.profiles set subscription_verified = true;
  end if;
end;
$$;

alter table public.notifications drop constraint if exists notifications_category_check;
alter table public.notifications
  add constraint notifications_category_check
  check (category in ('tickets', 'announcements', 'service_requests', 'customization', 'security'));

create table if not exists public.subscriber_link_requests (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  full_name text not null check (char_length(full_name) between 2 and 160),
  phone text not null check (char_length(phone) between 6 and 40),
  customer_reference text not null check (char_length(customer_reference) between 2 and 120),
  customer_note text check (customer_note is null or char_length(customer_note) <= 1000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  staff_note text check (staff_note is null or char_length(staff_note) <= 1000),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists subscriber_link_requests_one_pending_per_user
  on public.subscriber_link_requests (requester_id) where status = 'pending';
create index if not exists subscriber_link_requests_staff_queue
  on public.subscriber_link_requests (status, created_at desc);

alter table public.subscriber_link_requests enable row level security;

drop policy if exists "Customers can read own subscriber link requests" on public.subscriber_link_requests;
create policy "Customers can read own subscriber link requests"
  on public.subscriber_link_requests for select to authenticated
  using (requester_id = (select auth.uid()));

drop policy if exists "MFA verified staff can read subscriber link requests" on public.subscriber_link_requests;
create policy "MFA verified staff can read subscriber link requests"
  on public.subscriber_link_requests for select to authenticated
  using ((select public.is_staff()));

revoke all on public.subscriber_link_requests from anon, authenticated;
grant select on public.subscriber_link_requests to authenticated;

create table if not exists public.login_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  device_key_hash text not null check (char_length(device_key_hash) = 64),
  label text not null check (char_length(label) between 1 and 160),
  user_agent_preview text check (user_agent_preview is null or char_length(user_agent_preview) <= 240),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (user_id, device_key_hash)
);

create index if not exists login_devices_user_last_seen
  on public.login_devices (user_id, last_seen_at desc);

alter table public.login_devices enable row level security;

drop policy if exists "Users can read own login devices" on public.login_devices;
create policy "Users can read own login devices"
  on public.login_devices for select to authenticated
  using (user_id = (select auth.uid()));

drop policy if exists "Users can forget own login devices" on public.login_devices;
create policy "Users can forget own login devices"
  on public.login_devices for delete to authenticated
  using (user_id = (select auth.uid()));

revoke all on public.login_devices from anon, authenticated;
grant select, delete on public.login_devices to authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((auth.jwt() ->> 'aal') = 'aal2', false)
    and exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid())
        and lower(coalesce(p.role, '')) = 'admin'
    );
$$;

create or replace function public.is_manager()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((auth.jwt() ->> 'aal') = 'aal2', false)
    and exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid())
        and lower(coalesce(p.role, '')) = 'manager'
    );
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((auth.jwt() ->> 'aal') = 'aal2', false)
    and exists (
      select 1 from public.profiles p
      where p.id = (select auth.uid())
        and lower(coalesce(p.role, '')) in ('admin', 'manager')
    );
$$;

revoke all on function public.is_admin() from public;
revoke all on function public.is_manager() from public;
revoke all on function public.is_staff() from public;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_manager() to authenticated;
grant execute on function public.is_staff() to authenticated;

create or replace function public.submit_subscriber_link_request(
  p_full_name text,
  p_phone text,
  p_customer_reference text,
  p_customer_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_request_id bigint;
begin
  if v_user_id is null then raise exception 'authentication required'; end if;
  if char_length(trim(coalesce(p_full_name, ''))) not between 2 and 160 then raise exception 'enter your full name'; end if;
  if char_length(trim(coalesce(p_phone, ''))) not between 6 and 40 then raise exception 'enter a valid phone number'; end if;
  if char_length(trim(coalesce(p_customer_reference, ''))) not between 2 and 120 then raise exception 'enter your customer reference'; end if;
  if char_length(trim(coalesce(p_customer_note, ''))) > 1000 then raise exception 'note is too long'; end if;

  if exists (select 1 from public.profiles where id = v_user_id and subscription_verified) then
    raise exception 'this account is already linked';
  end if;

  insert into public.subscriber_link_requests (requester_id, full_name, phone, customer_reference, customer_note)
  values (v_user_id, trim(p_full_name), trim(p_phone), trim(p_customer_reference), nullif(trim(coalesce(p_customer_note, '')), ''))
  returning id into v_request_id;

  insert into public.notifications (recipient_id, category, event_type, title, body, href, source_type, source_id)
  select p.id, 'service_requests', 'subscriber_link_requested', 'Subscriber link request',
    trim(p_full_name) || ' submitted a subscription-link request.',
    case when p.role = 'manager' then '/manager/subscriber-links' else '/admin/subscriber-links' end,
    'subscriber_link_request', v_request_id::text
  from public.profiles p where lower(p.role) in ('admin', 'manager');

  return v_request_id;
exception
  when unique_violation then raise exception 'a link request is already pending';
end;
$$;

revoke all on function public.submit_subscriber_link_request(text, text, text, text) from public;
grant execute on function public.submit_subscriber_link_request(text, text, text, text) to authenticated;

create or replace function public.review_subscriber_link_request(
  p_request_id bigint,
  p_decision text,
  p_staff_note text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_request public.subscriber_link_requests%rowtype;
begin
  if not public.is_staff() then raise exception 'MFA-verified staff access required'; end if;
  if p_decision not in ('approved', 'rejected') then raise exception 'invalid review decision'; end if;
  if char_length(trim(coalesce(p_staff_note, ''))) > 1000 then raise exception 'staff note is too long'; end if;

  select * into v_request from public.subscriber_link_requests
  where id = p_request_id and status = 'pending' for update;
  if not found then raise exception 'pending request not found'; end if;

  update public.subscriber_link_requests set
    status = p_decision,
    staff_note = nullif(trim(coalesce(p_staff_note, '')), ''),
    reviewed_by = auth.uid(), reviewed_at = now(), updated_at = now()
  where id = p_request_id;

  if p_decision = 'approved' then
    update public.profiles set subscription_verified = true, updated_at = now()
    where id = v_request.requester_id;
  end if;

  insert into public.notifications (recipient_id, category, event_type, title, body, href, source_type, source_id)
  values (
    v_request.requester_id,
    'service_requests',
    'subscriber_link_' || p_decision,
    case when p_decision = 'approved' then 'Subscription linked' else 'Link request needs attention' end,
    case when p_decision = 'approved'
      then 'Your Centrum subscription was linked to this portal account.'
      else 'Your subscription-link request was not approved. Open Account Settings for details.' end,
    '/portal/account#subscription-link',
    'subscriber_link_request',
    p_request_id::text
  );
end;
$$;

revoke all on function public.review_subscriber_link_request(bigint, text, text) from public;
grant execute on function public.review_subscriber_link_request(bigint, text, text) to authenticated;

comment on column public.profiles.subscription_verified is
  'True only for pre-existing accounts or accounts approved by Centrum staff through the subscriber-link workflow.';
comment on table public.login_devices is
  'Hashed browser identifiers used to detect a first login from a browser. Raw device IDs are never stored.';
