begin;

-- Customer-safe network snapshot. This avoids exposing the full nodes table to
-- customers while still giving each signed-in customer the live state of only
-- the node assigned to their profile.
create or replace function public.get_my_network_status()
returns table (
  node_id uuid,
  node_name text,
  monitor_enabled boolean,
  probe_status text,
  latency_ms integer,
  last_checked_at timestamptz,
  last_seen_at timestamptz,
  maintenance_mode boolean,
  maintenance_message text,
  global_maintenance boolean,
  monitor_heartbeat_at text
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select
    p.node_id,
    n.name,
    coalesce(n.monitor_enabled, false),
    coalesce(n.probe_status, 'unknown'),
    n.latency_ms,
    n.last_checked_at,
    n.last_seen_at,
    coalesce(n.maintenance_mode, false),
    n.maintenance_message,
    coalesce((select lower(value) = 'true' from public.system_settings where key = 'global_maintenance'), false),
    nullif((select value from public.system_settings where key = 'monitor_heartbeat_at'), '')
  from public.profiles p
  left join public.nodes n on n.id = p.node_id
  where p.id = auth.uid();
$$;

revoke all on function public.get_my_network_status() from public;
grant execute on function public.get_my_network_status() to authenticated;

create table if not exists public.service_customization_requests (
  id bigint generated by default as identity primary key,
  customer_id uuid null references auth.users(id) on delete set null,
  full_name text not null,
  email text not null,
  phone text,
  address text,
  service_type text not null default 'home',
  people_count text,
  device_count text,
  usage_types text[] not null default '{}',
  budget_range text,
  preferred_plan_id bigint null references public.plans(id) on delete set null,
  preferred_plan_name text,
  current_provider text,
  notes text,
  status text not null default 'new' check (status in ('new', 'contacted', 'completed', 'closed')),
  email_sent_at timestamptz,
  email_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists service_customization_requests_created_idx on public.service_customization_requests(created_at desc);
create index if not exists service_customization_requests_status_idx on public.service_customization_requests(status);

alter table public.service_customization_requests enable row level security;

drop policy if exists "Admins can read customization requests" on public.service_customization_requests;
create policy "Admins can read customization requests"
on public.service_customization_requests for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can update customization requests" on public.service_customization_requests;
create policy "Admins can update customization requests"
on public.service_customization_requests for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete customization requests" on public.service_customization_requests;
create policy "Admins can delete customization requests"
on public.service_customization_requests for delete
to authenticated
using (public.is_admin());

commit;
