-- Centrum Service — Manager role + administrator-controlled role assignment
-- Adds a restricted operations role without weakening public.is_admin().

-- ---------------------------------------------------------------------------
-- ROLE DOMAIN
-- ---------------------------------------------------------------------------

alter table public.profiles
  drop constraint if exists profiles_role_check;

alter table public.profiles
  add constraint profiles_role_check
  check (role = any (array['customer'::text, 'manager'::text, 'admin'::text, 'support'::text]));

create or replace function public.is_manager()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.role, '')) = 'manager'
  );
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(coalesce(p.role, '')) in ('admin', 'manager')
  );
$$;

revoke all on function public.is_manager() from public, anon;
revoke all on function public.is_staff() from public, anon;
grant execute on function public.is_manager() to authenticated, service_role;
grant execute on function public.is_staff() to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- ROLE-CHANGE AUDIT + PROFILE GUARD
-- ---------------------------------------------------------------------------

create table if not exists public.role_change_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  target_id uuid references auth.users(id) on delete set null,
  old_role text not null,
  new_role text not null,
  changed_at timestamptz not null default now()
);

alter table public.role_change_audit enable row level security;

revoke all on table public.role_change_audit from anon;
grant select on table public.role_change_audit to authenticated;
grant select, insert, update, delete on table public.role_change_audit to service_role;

alter table public.role_change_audit
  drop constraint if exists role_change_audit_old_role_check;
alter table public.role_change_audit
  add constraint role_change_audit_old_role_check
  check (old_role = any (array['customer'::text, 'manager'::text, 'admin'::text, 'support'::text]));

alter table public.role_change_audit
  drop constraint if exists role_change_audit_new_role_check;
alter table public.role_change_audit
  add constraint role_change_audit_new_role_check
  check (new_role = any (array['customer'::text, 'manager'::text, 'admin'::text, 'support'::text]));

drop policy if exists "Admins can view role change audit" on public.role_change_audit;
create policy "Admins can view role change audit"
on public.role_change_audit
for select
to authenticated
using ((select public.is_admin()));

create or replace function private.centrum_guard_profile_update()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  -- Trusted server-side maintenance may still repair profile rows.
  if current_user in ('postgres', 'service_role', 'supabase_admin') then
    return new;
  end if;

  -- Managers may update operational customer fields, but never identity,
  -- authorization, creation metadata, or the network-node assignment.
  if public.is_manager() then
    if old.role <> 'customer' then
      raise exception 'managers may only modify customer profiles';
    end if;

    if new.id is distinct from old.id
       or new.role is distinct from old.role
       or new.created_at is distinct from old.created_at
       or new.node_id is distinct from old.node_id then
      raise exception 'managers cannot modify protected customer fields';
    end if;

    return new;
  end if;

  if new.role is distinct from old.role then
    if not public.is_admin() then
      raise exception 'only administrators can change account roles';
    end if;

    if old.id = auth.uid() then
      raise exception 'administrators cannot change their own role';
    end if;

    if old.role = 'admin' and new.role <> 'admin'
       and (select count(*) from public.profiles where role = 'admin') <= 1 then
      raise exception 'the final administrator cannot be demoted';
    end if;
  end if;

  return new;
end;
$$;

revoke all on function private.centrum_guard_profile_update() from public, anon, authenticated;
grant execute on function private.centrum_guard_profile_update() to service_role;

create or replace function private.centrum_audit_profile_role_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.role is distinct from old.role then
    insert into public.role_change_audit (actor_id, target_id, old_role, new_role)
    values (auth.uid(), new.id, old.role, new.role);
  end if;
  return new;
end;
$$;

revoke all on function private.centrum_audit_profile_role_change() from public, anon, authenticated;
grant execute on function private.centrum_audit_profile_role_change() to service_role;

drop trigger if exists centrum_guard_profile_update on public.profiles;
create trigger centrum_guard_profile_update
before update on public.profiles
for each row execute function private.centrum_guard_profile_update();

drop trigger if exists centrum_audit_profile_role_change on public.profiles;
create trigger centrum_audit_profile_role_change
after update of role on public.profiles
for each row execute function private.centrum_audit_profile_role_change();

-- ---------------------------------------------------------------------------
-- MANAGER DATA-API ACCESS
-- Existing administrator policies remain unchanged and admin-only.
-- ---------------------------------------------------------------------------

-- Profiles: operational management of customer rows only.
grant select, update on table public.profiles to authenticated;

drop policy if exists "Managers can read customer profiles" on public.profiles;
create policy "Managers can read customer profiles"
on public.profiles for select to authenticated
using ((select public.is_manager()) and role = 'customer');

drop policy if exists "Managers can update customer profiles" on public.profiles;
create policy "Managers can update customer profiles"
on public.profiles for update to authenticated
using ((select public.is_manager()) and role = 'customer')
with check ((select public.is_manager()) and role = 'customer');

-- Tickets and staff replies.
grant select, update on table public.tickets to authenticated;
grant select, insert on table public.ticket_updates to authenticated;

drop policy if exists "Managers can read tickets" on public.tickets;
create policy "Managers can read tickets"
on public.tickets for select to authenticated
using ((select public.is_manager()));

drop policy if exists "Managers can update tickets" on public.tickets;
create policy "Managers can update tickets"
on public.tickets for update to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

drop policy if exists "Managers can read ticket updates" on public.ticket_updates;
create policy "Managers can read ticket updates"
on public.ticket_updates for select to authenticated
using ((select public.is_manager()));

drop policy if exists "Managers can create ticket updates" on public.ticket_updates;
create policy "Managers can create ticket updates"
on public.ticket_updates for insert to authenticated
with check ((select public.is_manager()));

-- Realtime live chat.
grant select, update on table public.live_chat_sessions to authenticated;
grant select, insert on table public.live_chat_messages to authenticated;

drop policy if exists "Managers can read live chats" on public.live_chat_sessions;
create policy "Managers can read live chats"
on public.live_chat_sessions for select to authenticated
using ((select public.is_manager()));

drop policy if exists "Managers can update live chats" on public.live_chat_sessions;
create policy "Managers can update live chats"
on public.live_chat_sessions for update to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

drop policy if exists "Managers can read live chat messages" on public.live_chat_messages;
create policy "Managers can read live chat messages"
on public.live_chat_messages for select to authenticated
using ((select public.is_manager()));

drop policy if exists "Managers can send live chat messages" on public.live_chat_messages;
create policy "Managers can send live chat messages"
on public.live_chat_messages for insert to authenticated
with check ((select public.is_manager()));

-- Technician/service requests.
grant select, update on table public.service_requests to authenticated;

drop policy if exists "Managers can read service requests" on public.service_requests;
create policy "Managers can read service requests"
on public.service_requests for select to authenticated
using ((select public.is_manager()));

drop policy if exists "Managers can update service requests" on public.service_requests;
create policy "Managers can update service requests"
on public.service_requests for update to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

-- Customization/recommendation requests. No manager delete policy.
grant select, update on table public.service_customization_requests to authenticated;

drop policy if exists "Managers can read customization requests" on public.service_customization_requests;
create policy "Managers can read customization requests"
on public.service_customization_requests for select to authenticated
using ((select public.is_manager()));

drop policy if exists "Managers can update customization requests" on public.service_customization_requests;
create policy "Managers can update customization requests"
on public.service_customization_requests for update to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

-- Announcements: create/edit/publish, but no permanent deletion.
grant select, insert, update on table public.announcements to authenticated;

drop policy if exists "Managers can read announcements" on public.announcements;
create policy "Managers can read announcements"
on public.announcements for select to authenticated
using ((select public.is_manager()));

drop policy if exists "Managers can create announcements" on public.announcements;
create policy "Managers can create announcements"
on public.announcements for insert to authenticated
with check ((select public.is_manager()));

drop policy if exists "Managers can update announcements" on public.announcements;
create policy "Managers can update announcements"
on public.announcements for update to authenticated
using ((select public.is_manager()))
with check ((select public.is_manager()));

-- Billing: managers may record and review payments, but not edit/delete history.
grant select, insert on table public.payments to authenticated;

drop policy if exists "Managers can read payments" on public.payments;
create policy "Managers can read payments"
on public.payments for select to authenticated
using ((select public.is_manager()));

drop policy if exists "Managers can record payments" on public.payments;
create policy "Managers can record payments"
on public.payments for insert to authenticated
with check ((select public.is_manager()));

-- ---------------------------------------------------------------------------
-- STAFF IDENTITY IN TICKETS / LIVE CHAT
-- `is_admin` on message rows historically means "Centrum staff message".
-- ---------------------------------------------------------------------------

create or replace function public.set_ticket_update_identity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.user_id := auth.uid();
  new.is_admin := public.is_staff();
  return new;
end;
$$;

create or replace function public.set_live_chat_message_identity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.sender_id := auth.uid();
  new.is_admin := public.is_staff();
  return new;
end;
$$;

create or replace function public.guard_live_chat_session_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  -- Internal timestamp touch from the SECURITY DEFINER trigger.
  if current_user = 'postgres' then
    return new;
  end if;

  if public.is_staff() then
    return new;
  end if;

  if auth.uid() is null or old.customer_id <> auth.uid() then
    raise exception 'not allowed';
  end if;

  if new.id is distinct from old.id
     or new.customer_id is distinct from old.customer_id
     or new.started_at is distinct from old.started_at
     or new.updated_at is distinct from old.updated_at then
    raise exception 'customers may only close a live chat';
  end if;

  if old.status <> 'open' or new.status <> 'closed' then
    raise exception 'customers may only close a live chat';
  end if;

  return new;
end;
$$;

-- Trigger-only helpers are not public RPC endpoints.
revoke execute on function public.set_ticket_update_identity() from public, anon, authenticated;
revoke execute on function public.set_live_chat_message_identity() from public, anon, authenticated;
revoke execute on function public.guard_live_chat_session_update() from public, anon, authenticated;

-- Service role retains maintenance access to trigger functions.
grant execute on function public.set_ticket_update_identity() to service_role;
grant execute on function public.set_live_chat_message_identity() to service_role;
grant execute on function public.guard_live_chat_session_update() to service_role;

-- ---------------------------------------------------------------------------
-- OPERATIONAL NOTIFICATIONS FOR MANAGERS
-- Keep the existing helper name for trigger compatibility, but deliver new
-- ticket/request/customization alerts to both administrators and managers.
-- Manager links stay inside the restricted manager workspace.
-- ---------------------------------------------------------------------------

create or replace function private.centrum_notify_admins(
  p_category text,
  p_event_type text,
  p_title text,
  p_body text,
  p_href text,
  p_source_type text default null,
  p_source_id text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.notifications(
    recipient_id, category, event_type, title, body, href, source_type, source_id
  )
  select
    p.id,
    p_category,
    p_event_type,
    left(coalesce(p_title, 'Centrum notification'), 180),
    left(coalesce(p_body, ''), 500),
    left(
      case
        when lower(coalesce(p.role, '')) = 'manager' and p_category = 'service_requests'
          then '/manager?workspace=requests'
        when lower(coalesce(p.role, '')) = 'manager' and p_category = 'customization'
          then '/manager?workspace=customization'
        when lower(coalesce(p.role, '')) = 'manager' and p_category = 'tickets'
          then coalesce(p_href, '/manager?workspace=support')
        when lower(coalesce(p.role, '')) = 'manager'
          then '/manager'
        else coalesce(p_href, '/admin')
      end,
      500
    ),
    p_source_type,
    p_source_id
  from public.profiles p
  where lower(coalesce(p.role, '')) in ('admin', 'manager');
end;
$$;

revoke all on function private.centrum_notify_admins(text,text,text,text,text,text,text) from public, anon, authenticated;
grant execute on function private.centrum_notify_admins(text,text,text,text,text,text,text) to service_role;

create or replace function private.centrum_notification_announcement_published()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_should_notify boolean := false;
begin
  if tg_op = 'INSERT' then
    v_should_notify := new.is_published and new.starts_at <= now();
  elsif tg_op = 'UPDATE' then
    v_should_notify := new.is_published and new.starts_at <= now()
      and (old.is_published is distinct from true);
  end if;

  if v_should_notify then
    insert into public.notifications(
      recipient_id, category, event_type, title, body, href, source_type, source_id
    )
    select
      p.id,
      'announcements',
      'announcement_published',
      left(new.title, 180),
      left(regexp_replace(new.body, '\\s+', ' ', 'g'), 500),
      '/portal/dashboard?workspace=support&highlightAnnouncement=' || new.id,
      'announcement',
      new.id::text
    from public.profiles p
    where lower(coalesce(p.role, 'customer')) = 'customer';
  end if;

  return new;
end;
$$;

revoke all on function private.centrum_notification_announcement_published() from public, anon, authenticated;
grant execute on function private.centrum_notification_announcement_published() to service_role;
