-- Centrum Service V1 security hardening snapshot.
-- The equivalent production migrations were already applied to Supabase on 2026-08-20.
-- Keep this file in source control. Do NOT rerun it against production just because
-- you copied it into the project; Supabase already records security_rls_hardening_v1
-- and security_function_hardening_v1 as applied migrations.

begin;

create table if not exists public.form_rate_limits (
  id bigint generated by default as identity primary key,
  form_name text not null,
  ip_hash text not null,
  created_at timestamptz not null default now()
);
alter table public.form_rate_limits enable row level security;
revoke all privileges on table public.form_rate_limits from public, anon, authenticated;
grant select, insert, delete on table public.form_rate_limits to service_role;
grant usage, select on sequence public.form_rate_limits_id_seq to service_role;
create index if not exists form_rate_limits_lookup_idx
  on public.form_rate_limits(form_name, ip_hash, created_at desc);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid())
      and lower(coalesce(p.role, '')) = 'admin'
  );
$$;
revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated, service_role;

create or replace function public.get_my_network_status()
returns table (
  node_id uuid, node_name text, monitor_enabled boolean, probe_status text,
  latency_ms integer, last_checked_at timestamptz, last_seen_at timestamptz,
  maintenance_mode boolean, maintenance_message text,
  global_maintenance boolean, monitor_heartbeat_at text
)
language sql stable security definer set search_path = '' as $$
  select p.node_id, n.name, coalesce(n.monitor_enabled,false),
    coalesce(n.probe_status,'unknown'), n.latency_ms, n.last_checked_at,
    n.last_seen_at, coalesce(n.maintenance_mode,false), n.maintenance_message,
    coalesce((select lower(s.value)='true' from public.system_settings s where s.key='global_maintenance'),false),
    nullif((select s.value from public.system_settings s where s.key='monitor_heartbeat_at'),'')
  from public.profiles p
  left join public.nodes n on n.id=p.node_id
  where p.id=(select auth.uid());
$$;
revoke all on function public.get_my_network_status() from public, anon;
grant execute on function public.get_my_network_status() to authenticated, service_role;

-- Remove legacy/broad policies.
drop policy if exists "Authenticated users can view nodes" on public.nodes;
drop policy if exists "users update own profile" on public.profiles;
drop policy if exists "users read own profile" on public.profiles;
drop policy if exists "admin/support read all profiles" on public.profiles;
drop policy if exists "public read plans" on public.plans;
drop policy if exists "admin/support manage plans" on public.plans;
drop policy if exists "admin/support manage all tickets" on public.tickets;
drop policy if exists "customer creates own tickets" on public.tickets;
drop policy if exists "customer reads own tickets" on public.tickets;
drop policy if exists "customer updates own open tickets" on public.tickets;
drop policy if exists "Anyone can submit contact inquiries" on public.contact_inquiries;
drop policy if exists "Anyone can read network status" on public.system_settings;
drop policy if exists "admin/support manage contact requests" on public.contact_requests;
drop policy if exists "admin/support read contact requests" on public.contact_requests;
drop policy if exists "public insert contact requests" on public.contact_requests;
drop policy if exists "admin/support manage coverage" on public.coverage_areas;
drop policy if exists "public read coverage" on public.coverage_areas;
drop policy if exists "admin/support insert messages" on public.ticket_messages;
drop policy if exists "admin/support manage messages" on public.ticket_messages;
drop policy if exists "admin/support read all messages" on public.ticket_messages;
drop policy if exists "customer insert message in own tickets" on public.ticket_messages;
drop policy if exists "customer read messages in own tickets" on public.ticket_messages;

-- Profiles: customers read themselves; only admin policies permit updates.
drop policy if exists "Customers can read own profile" on public.profiles;
create policy "Customers can read own profile" on public.profiles
for select to authenticated
using ((select auth.uid()) is not null and id=(select auth.uid()));
drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles" on public.profiles
for all to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

-- Public catalogs are read-only except for admins.
drop policy if exists "Public can view active plans" on public.plans;
create policy "Public can view active plans" on public.plans
for select to anon, authenticated using (is_active=true);
drop policy if exists "Customers can view assigned plan" on public.plans;
create policy "Customers can view assigned plan" on public.plans
for select to authenticated using (exists (
  select 1 from public.profiles p
  where p.id=(select auth.uid()) and p.plan_id=plans.id
));
drop policy if exists "Admins can view all plans" on public.plans;
create policy "Admins can view all plans" on public.plans
for select to authenticated using ((select public.is_admin()));
drop policy if exists "Public can view active coverage regions" on public.coverage_regions;
create policy "Public can view active coverage regions" on public.coverage_regions
for select to anon, authenticated using (is_active=true);

-- Customer support ownership.
drop policy if exists "Customers can create own tickets" on public.tickets;
create policy "Customers can create own tickets" on public.tickets
for insert to authenticated with check (
  (select auth.uid()) is not null and customer_id=(select auth.uid())
  and status='open' and priority='normal' and not (select public.is_admin())
);
drop policy if exists "Customers can view own tickets" on public.tickets;
create policy "Customers can view own tickets" on public.tickets
for select to authenticated using (customer_id=(select auth.uid()) or (select public.is_admin()));
drop policy if exists "Admins can update tickets" on public.tickets;
create policy "Admins can update tickets" on public.tickets
for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists "Participants can view ticket updates" on public.ticket_updates;
create policy "Participants can view ticket updates" on public.ticket_updates
for select to authenticated using (exists (
  select 1 from public.tickets t where t.id=ticket_updates.ticket_id
  and (t.customer_id=(select auth.uid()) or (select public.is_admin()))
));
drop policy if exists "Participants can create ticket updates" on public.ticket_updates;
create policy "Participants can create ticket updates" on public.ticket_updates
for insert to authenticated with check (exists (
  select 1 from public.tickets t where t.id=ticket_updates.ticket_id
  and (t.customer_id=(select auth.uid()) or (select public.is_admin()))
));

drop policy if exists "Customers can read own payments" on public.payments;
create policy "Customers can read own payments" on public.payments
for select to authenticated using ((select auth.uid()) is not null and customer_id=(select auth.uid()));

drop policy if exists "Customers can create own service requests" on public.service_requests;
create policy "Customers can create own service requests" on public.service_requests
for insert to authenticated with check (
  (select auth.uid()) is not null and customer_id=(select auth.uid())
  and status='submitted' and admin_note is null
);
drop policy if exists "Customers can read own service requests" on public.service_requests;
create policy "Customers can read own service requests" on public.service_requests
for select to authenticated using ((select auth.uid()) is not null and customer_id=(select auth.uid()));

drop policy if exists "Customers can start own live chats" on public.live_chat_sessions;
create policy "Customers can start own live chats" on public.live_chat_sessions
for insert to authenticated with check (
  (select auth.uid()) is not null and customer_id=(select auth.uid()) and status='open'
);
drop policy if exists "Customers can read own live chats" on public.live_chat_sessions;
create policy "Customers can read own live chats" on public.live_chat_sessions
for select to authenticated using (customer_id=(select auth.uid()) or (select public.is_admin()));
drop policy if exists "Customers can close own live chats" on public.live_chat_sessions;
create policy "Customers can close own live chats" on public.live_chat_sessions
for update to authenticated
using (customer_id=(select auth.uid()) or (select public.is_admin()))
with check (customer_id=(select auth.uid()) or (select public.is_admin()));

create or replace function public.guard_live_chat_session_update()
returns trigger language plpgsql set search_path='' as $$
begin
  if public.is_admin() then return new; end if;
  if auth.uid() is null or old.customer_id <> auth.uid() then raise exception 'not allowed'; end if;
  if new.id is distinct from old.id
     or new.customer_id is distinct from old.customer_id
     or new.started_at is distinct from old.started_at
     or new.updated_at is distinct from old.updated_at then
    raise exception 'only chat status can be changed';
  end if;
  if new.status <> 'closed' then raise exception 'customers may only close a live chat'; end if;
  return new;
end;
$$;
drop trigger if exists guard_live_chat_session_customer_update on public.live_chat_sessions;
create trigger guard_live_chat_session_customer_update before update on public.live_chat_sessions
for each row execute function public.guard_live_chat_session_update();

drop policy if exists "Participants can read live chat messages" on public.live_chat_messages;
create policy "Participants can read live chat messages" on public.live_chat_messages
for select to authenticated using (exists (
  select 1 from public.live_chat_sessions s where s.id=live_chat_messages.session_id
  and (s.customer_id=(select auth.uid()) or (select public.is_admin()))
));
drop policy if exists "Participants can send live chat messages" on public.live_chat_messages;
create policy "Participants can send live chat messages" on public.live_chat_messages
for insert to authenticated with check (exists (
  select 1 from public.live_chat_sessions s where s.id=live_chat_messages.session_id
  and s.status='open' and (s.customer_id=(select auth.uid()) or (select public.is_admin()))
));

-- Minimize table grants. RLS remains the authorization boundary.
revoke all privileges on table public.announcements, public.contact_inquiries,
  public.contact_requests, public.coverage_areas, public.coverage_regions,
  public.live_chat_messages, public.live_chat_sessions, public.nodes,
  public.payments, public.plans, public.profiles,
  public.service_customization_requests, public.service_requests,
  public.system_settings, public.ticket_messages, public.ticket_updates,
  public.tickets from anon, authenticated;
grant select on table public.plans, public.coverage_regions to anon;
grant select, update on table public.profiles to authenticated;
grant select, insert, update on table public.tickets to authenticated;
grant select, insert on table public.ticket_updates to authenticated;
grant select, insert, delete on table public.payments to authenticated;
grant select, insert, update on table public.service_requests to authenticated;
grant select, insert, update on table public.live_chat_sessions to authenticated;
grant select, insert on table public.live_chat_messages to authenticated;
grant select, update, delete on table public.contact_inquiries to authenticated;
grant select, insert, update, delete on table public.nodes to authenticated;
grant select, insert, update on table public.system_settings to authenticated;
grant select, insert, update, delete on table public.plans, public.coverage_regions, public.announcements to authenticated;
grant select, update, delete on table public.service_customization_requests to authenticated;

create index if not exists tickets_customer_id_rls_idx on public.tickets(customer_id);
create index if not exists payments_customer_id_rls_idx on public.payments(customer_id);
create index if not exists service_requests_customer_id_rls_idx on public.service_requests(customer_id);
create index if not exists live_chat_sessions_customer_id_rls_idx on public.live_chat_sessions(customer_id);
create index if not exists ticket_updates_ticket_id_rls_idx on public.ticket_updates(ticket_id);
create index if not exists live_chat_messages_session_id_rls_idx on public.live_chat_messages(session_id);

-- Function hardening from the second production migration.
alter function public.set_updated_at() set search_path='';
alter function public.handle_new_user() set search_path='';
alter function public.is_admin_or_support() set search_path='';
alter function public.touch_system_setting() set search_path='';
alter function public.touch_updated_at() set search_path='';
alter function public.centrum_set_updated_at() set search_path='';
revoke all on function public.advance_customer_renewal_after_payment() from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.set_live_chat_message_identity() from public, anon, authenticated;
revoke all on function public.set_ticket_update_identity() from public, anon, authenticated;
revoke all on function public.touch_live_chat_session() from public, anon, authenticated;
revoke all on function public.is_admin_or_support() from public, anon, authenticated;
grant execute on function public.advance_customer_renewal_after_payment(), public.handle_new_user(),
  public.set_live_chat_message_identity(), public.set_ticket_update_identity(),
  public.touch_live_chat_session(), public.is_admin_or_support() to service_role;

drop policy if exists "Browser access denied" on public.contact_requests;
create policy "Browser access denied" on public.contact_requests for all to anon, authenticated using(false) with check(false);
drop policy if exists "Browser access denied" on public.coverage_areas;
create policy "Browser access denied" on public.coverage_areas for all to anon, authenticated using(false) with check(false);
drop policy if exists "Browser access denied" on public.ticket_messages;
create policy "Browser access denied" on public.ticket_messages for all to anon, authenticated using(false) with check(false);
drop policy if exists "Browser access denied" on public.form_rate_limits;
create policy "Browser access denied" on public.form_rate_limits for all to anon, authenticated using(false) with check(false);

commit;
