-- Centrum Service V1: unified in-app notifications and per-user preferences.
-- Creates persistent notification records for support, announcements, service
-- requests and customization requests. UI reminder popups are driven by unread
-- rows; closing a popup does not mark the notification read.

begin;

create table if not exists public.notification_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  in_app_enabled boolean not null default true,
  ticket_notifications boolean not null default true,
  announcement_notifications boolean not null default true,
  service_request_notifications boolean not null default true,
  customization_notifications boolean not null default true,
  reminder_popups boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('tickets', 'announcements', 'service_requests', 'customization')),
  event_type text not null,
  title text not null,
  body text not null default '',
  href text not null,
  source_type text,
  source_id text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

alter table public.notification_preferences enable row level security;
alter table public.notifications enable row level security;

revoke all privileges on table public.notification_preferences, public.notifications from public, anon, authenticated;
grant select, insert, update on table public.notification_preferences to authenticated;
grant select on table public.notifications to authenticated;
grant update (read_at) on table public.notifications to authenticated;
grant all privileges on table public.notification_preferences, public.notifications to service_role;
grant usage, select on sequence public.notifications_id_seq to service_role;

create policy "Users can read own notification preferences"
on public.notification_preferences for select to authenticated
using ((select auth.uid()) is not null and user_id = (select auth.uid()));

create policy "Users can create own notification preferences"
on public.notification_preferences for insert to authenticated
with check ((select auth.uid()) is not null and user_id = (select auth.uid()));

create policy "Users can update own notification preferences"
on public.notification_preferences for update to authenticated
using ((select auth.uid()) is not null and user_id = (select auth.uid()))
with check ((select auth.uid()) is not null and user_id = (select auth.uid()));

create policy "Users can read own notifications"
on public.notifications for select to authenticated
using ((select auth.uid()) is not null and recipient_id = (select auth.uid()));

create policy "Users can mark own notifications read"
on public.notifications for update to authenticated
using ((select auth.uid()) is not null and recipient_id = (select auth.uid()))
with check ((select auth.uid()) is not null and recipient_id = (select auth.uid()));

create index if not exists notifications_recipient_unread_idx
  on public.notifications(recipient_id, created_at desc)
  where read_at is null;
create index if not exists notifications_recipient_created_idx
  on public.notifications(recipient_id, created_at desc);

-- Existing signed-in customers should be able to see the status of their own
-- customization requests so a notification can deep-link to useful context.
drop policy if exists "Customers can read own customization requests" on public.service_customization_requests;
create policy "Customers can read own customization requests"
on public.service_customization_requests for select to authenticated
using (
  (select auth.uid()) is not null
  and customer_id = (select auth.uid())
);

-- Seed defaults for existing accounts. Future accounts work with application
-- defaults until their first preference save, so no auth trigger is required.
insert into public.notification_preferences(user_id)
select p.id from public.profiles p
on conflict (user_id) do nothing;

-- Keep preference timestamps current without granting clients control of them.
create or replace function private.centrum_notification_preferences_touch()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
revoke all on function private.centrum_notification_preferences_touch() from public, anon, authenticated;

drop trigger if exists notification_preferences_touch_updated_at on public.notification_preferences;
create trigger notification_preferences_touch_updated_at
before update on public.notification_preferences
for each row execute function private.centrum_notification_preferences_touch();

-- Internal helpers. They are intentionally in the non-exposed private schema
-- and cannot be executed directly by browser roles.
create or replace function private.centrum_notify_user(
  p_recipient uuid,
  p_category text,
  p_event_type text,
  p_title text,
  p_body text,
  p_href text,
  p_source_type text default null,
  p_source_id text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_recipient is null then
    return;
  end if;

  insert into public.notifications(
    recipient_id, category, event_type, title, body, href, source_type, source_id
  ) values (
    p_recipient,
    p_category,
    p_event_type,
    left(coalesce(p_title, 'Centrum notification'), 180),
    left(coalesce(p_body, ''), 500),
    left(coalesce(p_href, '/portal/dashboard'), 500),
    p_source_type,
    p_source_id
  );
end;
$$;
revoke all on function private.centrum_notify_user(uuid,text,text,text,text,text,text,text) from public, anon, authenticated;

create or replace function private.centrum_notify_admins(
  p_category text,
  p_event_type text,
  p_title text,
  p_body text,
  p_href text,
  p_source_type text default null,
  p_source_id text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.notifications(
    recipient_id, category, event_type, title, body, href, source_type, source_id
  )
  select
    p.id,
    p_category,
    p_event_type,
    left(coalesce(p_title, 'Centrum notification'), 180),
    left(coalesce(p_body, ''), 500),
    left(coalesce(p_href, '/admin'), 500),
    p_source_type,
    p_source_id
  from public.profiles p
  where lower(coalesce(p.role, '')) = 'admin';
end;
$$;
revoke all on function private.centrum_notify_admins(text,text,text,text,text,text,text) from public, anon, authenticated;

create or replace function private.centrum_notification_ticket_created()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.centrum_notify_admins(
    'tickets',
    'ticket_created',
    'New support ticket #' || new.id,
    left(regexp_replace(new.subject, '\s+', ' ', 'g'), 220),
    '/portal/tickets/' || new.id,
    'ticket',
    new.id::text
  );
  return new;
end;
$$;
revoke all on function private.centrum_notification_ticket_created() from public, anon, authenticated;

drop trigger if exists centrum_notification_ticket_created on public.tickets;
create trigger centrum_notification_ticket_created
after insert on public.tickets
for each row execute function private.centrum_notification_ticket_created();

create or replace function private.centrum_notification_ticket_reply()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_ticket public.tickets%rowtype;
  v_preview text;
begin
  select * into v_ticket from public.tickets where id = new.ticket_id;
  if not found then return new; end if;

  v_preview := left(regexp_replace(coalesce(new.message, ''), '\s+', ' ', 'g'), 220);

  if new.is_admin then
    perform private.centrum_notify_user(
      v_ticket.customer_id,
      'tickets',
      'ticket_reply',
      'Centrum replied to ticket #' || v_ticket.id,
      v_preview,
      '/portal/tickets/' || v_ticket.id,
      'ticket_update',
      new.id::text
    );
  else
    perform private.centrum_notify_admins(
      'tickets',
      'ticket_reply',
      'Customer replied to ticket #' || v_ticket.id,
      v_preview,
      '/portal/tickets/' || v_ticket.id,
      'ticket_update',
      new.id::text
    );
  end if;

  return new;
end;
$$;
revoke all on function private.centrum_notification_ticket_reply() from public, anon, authenticated;

drop trigger if exists centrum_notification_ticket_reply on public.ticket_updates;
create trigger centrum_notification_ticket_reply
after insert on public.ticket_updates
for each row execute function private.centrum_notification_ticket_reply();

create or replace function private.centrum_notification_ticket_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status is distinct from old.status then
    perform private.centrum_notify_user(
      new.customer_id,
      'tickets',
      'ticket_status_' || new.status,
      'Ticket #' || new.id || ' status changed',
      'Your support ticket is now ' || replace(new.status, '_', ' ') || '.',
      '/portal/tickets/' || new.id,
      'ticket',
      new.id::text || ':' || new.status
    );
  end if;
  return new;
end;
$$;
revoke all on function private.centrum_notification_ticket_status() from public, anon, authenticated;

drop trigger if exists centrum_notification_ticket_status on public.tickets;
create trigger centrum_notification_ticket_status
after update of status on public.tickets
for each row execute function private.centrum_notification_ticket_status();

create or replace function private.centrum_notification_service_request_created()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_type text;
begin
  v_type := initcap(replace(new.request_type, '_', ' '));
  perform private.centrum_notify_admins(
    'service_requests',
    'service_request_created',
    'New ' || v_type || ' request #' || new.id,
    left(regexp_replace(new.details, '\s+', ' ', 'g'), 220),
    '/admin/operations?workspace=requests&highlight=' || new.id,
    'service_request',
    new.id::text
  );
  return new;
end;
$$;
revoke all on function private.centrum_notification_service_request_created() from public, anon, authenticated;

drop trigger if exists centrum_notification_service_request_created on public.service_requests;
create trigger centrum_notification_service_request_created
after insert on public.service_requests
for each row execute function private.centrum_notification_service_request_created();

create or replace function private.centrum_notification_service_request_updated()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_body text;
begin
  if new.status is distinct from old.status or new.admin_note is distinct from old.admin_note then
    v_body := 'Status: ' || initcap(replace(new.status, '_', ' '));
    if new.admin_note is not null and btrim(new.admin_note) <> '' then
      v_body := v_body || '. Centrum: ' || left(regexp_replace(new.admin_note, '\s+', ' ', 'g'), 260);
    end if;

    perform private.centrum_notify_user(
      new.customer_id,
      'service_requests',
      'service_request_updated',
      'Service request #' || new.id || ' updated',
      v_body,
      '/portal/dashboard?workspace=service&highlightRequest=' || new.id,
      'service_request',
      new.id::text || ':' || extract(epoch from now())::bigint::text
    );
  end if;
  return new;
end;
$$;
revoke all on function private.centrum_notification_service_request_updated() from public, anon, authenticated;

drop trigger if exists centrum_notification_service_request_updated on public.service_requests;
create trigger centrum_notification_service_request_updated
after update of status, admin_note on public.service_requests
for each row execute function private.centrum_notification_service_request_updated();

create or replace function private.centrum_notification_customization_created()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_body text;
begin
  v_body := new.full_name;
  if new.preferred_plan_name is not null and btrim(new.preferred_plan_name) <> '' then
    v_body := v_body || ' · Preferred plan: ' || new.preferred_plan_name;
  elsif cardinality(new.usage_types) > 0 then
    v_body := v_body || ' · ' || array_to_string(new.usage_types, ', ');
  end if;

  perform private.centrum_notify_admins(
    'customization',
    'customization_created',
    'New customization request #' || new.id,
    left(v_body, 300),
    '/admin/operations?workspace=customization&highlight=' || new.id,
    'service_customization_request',
    new.id::text
  );
  return new;
end;
$$;
revoke all on function private.centrum_notification_customization_created() from public, anon, authenticated;

drop trigger if exists centrum_notification_customization_created on public.service_customization_requests;
create trigger centrum_notification_customization_created
after insert on public.service_customization_requests
for each row execute function private.centrum_notification_customization_created();

create or replace function private.centrum_notification_customization_updated()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.customer_id is not null and new.status is distinct from old.status then
    perform private.centrum_notify_user(
      new.customer_id,
      'customization',
      'customization_status_' || new.status,
      'Customization request #' || new.id || ' updated',
      'Your service recommendation request is now ' || replace(new.status, '_', ' ') || '.',
      '/portal/dashboard?workspace=service&highlightCustomization=' || new.id,
      'service_customization_request',
      new.id::text || ':' || new.status
    );
  end if;
  return new;
end;
$$;
revoke all on function private.centrum_notification_customization_updated() from public, anon, authenticated;

drop trigger if exists centrum_notification_customization_updated on public.service_customization_requests;
create trigger centrum_notification_customization_updated
after update of status on public.service_customization_requests
for each row execute function private.centrum_notification_customization_updated();

create or replace function private.centrum_notification_announcement_published()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_should_notify boolean := false;
begin
  if tg_op = 'INSERT' then
    v_should_notify := new.is_published and new.starts_at <= now();
  elsif tg_op = 'UPDATE' then
    v_should_notify := new.is_published and new.starts_at <= now()
      and (old.is_published is distinct from true);
  end if;

  if v_should_notify then
    insert into public.notifications(
      recipient_id, category, event_type, title, body, href, source_type, source_id
    )
    select
      p.id,
      'announcements',
      'announcement_published',
      left(new.title, 180),
      left(regexp_replace(new.body, '\s+', ' ', 'g'), 500),
      '/portal/dashboard?workspace=support&highlightAnnouncement=' || new.id,
      'announcement',
      new.id::text
    from public.profiles p
    where lower(coalesce(p.role, 'customer')) <> 'admin';
  end if;

  return new;
end;
$$;
revoke all on function private.centrum_notification_announcement_published() from public, anon, authenticated;

drop trigger if exists centrum_notification_announcement_published on public.announcements;
create trigger centrum_notification_announcement_published
after insert or update of is_published on public.announcements
for each row execute function private.centrum_notification_announcement_published();

-- Postgres Changes is used for instant in-browser delivery, with polling as a
-- fallback. Supabase's 2026 Realtime restrictions lock the realtime schema,
-- but adding a public table to the existing publication remains the supported
-- pattern.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'notifications'
  ) then
    execute 'alter publication supabase_realtime add table public.notifications';
  end if;
end;
$$;

commit;
